### ISSUE TITLE
Create NPM package

### ISSUE THREAD

**Issue by medhi** [contributte/live-form-validation#31]
Would you please add this library to NPM? Thanks.

**Comment by Robyer** [comment]
I'm not familiar with NPM at all. And I don't do web development anymore, so unless this can be done easily with pull request (or similar simple one-time action), I don't want to spend my time on this.

I recommend that you or someone else handle NPM management of this library.

**Comment by f3l1x** [comment]
@Robyer I can hadle it if you want.

**Comment by namo-R** [comment]
some progress ? ;)

**Comment by f3l1x** [comment]
@namo-R Yep, sorry for delay, I was moving into the new house. I'll keep an eye on it.

**Comment by f3l1x** [comment]
Solved by @jelen07 via #35

**Comment by jetelusmaximus** [comment]
Hello, I would like to follow up on this issue to suggest stands for source and distribution: folders src/ and dist/.
What do you think about it? Thanks.

**Comment by f3l1x** [comment]
@jetelusmaximus Well, this package is written in pure JS, what's the point of dist folder? Do you have any plan to convert it to ES6?

**Comment by jetelusmaximus** [comment]
@f3l1x Thank you for quick reply. I mention this folders primarily with idea to create a minified file. Which I can install from git with NPM and load min version instead of original.

**Comment by f3l1x** [comment]
I see, could you please create and extra issue, something like, Support minified version.

**Comment by jetelusmaximus** [comment]
Great, thank you :)
