### ISSUE TITLE
Support for Nette 3

### ISSUE THREAD

**Issue by mabezdek** [contributte/live-form-validation#58]
Hi guys,

It is supports Nette 3?

Thankx!

**Comment by mabar** [comment]
#57

**Comment by radimvaculik** [comment]
Done @ https://github.com/contributte/live-form-validation/commit/eb847873eb3483c73382fdbd961b7c2e9dd08365

**Comment by jaroslavlibal** [comment]
Would be great to release a version and upgrade package.json on that occasion if possible. Thanks!

**Comment by jaroslavlibal** [comment]
Any chance for a release and tag? @f3l1x

**Comment by f3l1x** [comment]
Solved https://www.npmjs.com/package/live-form-validation
